name: Vicky Chow
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7903226
title: 'Vicky Chow, pianist'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0C0C0C'
    - '#CFBDB4'
    - '#392717'
    - '#788688'
    - '#B44B01'
  brandStrength: 0.6039426
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.6469534
purpose: []
