name: Vicky Chow
favicon: null
layout_spectrum: 0
typography_spectrum: 0.90366
title: 'Vicky Chow, pianist'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#384d5e'
    - '#b7b7b7'
    - '#737373'
    - '#1c1c1c'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
