name: Vicky Chow
favicon: null
layout_spectrum: 0.84393
typography_spectrum: 0.90366
title: 'Vicky Chow, pianist'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#030303'
    - '#bbb3a9'
    - '#9e917c'
    - '#6b563e'
  brandStrength: 1
  lightness: 1
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
