title: 'Vicky Chow, pianist'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6326165
  brandStrength: 0.7562724
  lightness: 0.7956989
  brandColors:
    - '#010003'
    - '#FDFDFC'
    - '#5C425C'
    - '#A3887F'
    - '#77170D'
  rhythmicContrast: 0.6146954
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Vicky Chow
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.90366
layout_spectrum: 0
